from pathlib import Path
p = Path('NativeGameplayManifest.cppm')
s = p.read_text()
s = s.replace('if (!attachment.Target.IsValid() || !scene.Contains(attachment.Target))', 'if (!attachment.Target || !scene.Contains(attachment.Target))')
s = s.replace('if (!attachment->Target.IsValid() || attachment->TypeName.empty())', 'if (!attachment->Target || attachment->TypeName.empty())')
s = s.replace('if (!attachment.Target.IsValid() || attachment.TypeName.empty())', 'if (!attachment.Target || attachment.TypeName.empty())')
s = s.replace('attachment.Target = Entity{ ParseUInt64(tokens[1], lineNumber, "entity") };', 'const auto entityValue = ParseUInt64(tokens[1], lineNumber, "entity");\n                if (entityValue > std::numeric_limits<std::uint32_t>::max())\n                    throw NativeGameplayManifestFormatError(lineNumber, tokens[1].Column, "entity exceeds 32-bit scene identity range");\n                attachment.Target = Entity{ static_cast<std::uint32_t>(entityValue) };')
s = s.replace('value = Entity{ ParseUInt64(tokens[3], lineNumber, "entity property") };', 'const auto entityValue = ParseUInt64(tokens[3], lineNumber, "entity property");\n                    if (entityValue > std::numeric_limits<std::uint32_t>::max())\n                        throw NativeGameplayManifestFormatError(lineNumber, tokens[3].Column, "entity property exceeds 32-bit scene identity range");\n                    value = Entity{ static_cast<std::uint32_t>(entityValue) };')
s = s.replace('if (!stream.eof() || !std::isfinite(value))', 'if (!stream || !stream.eof() || !std::isfinite(value))')
p.write_text(s)
Path('.github/workflows/fix-native-manifest-entity.yml').unlink()
Path('.github/scripts/fix_native_manifest_entity.py').unlink()
